### ISSUE TITLE
More details requested for how to set up

### ISSUE THREAD

**Issue by ianfhunter** [1drturtle/avrae-autoupdate#1]
Hi, I don't understand how to get the avrae token:
> Get your Avrae Token. You can do this by going to [the Avrae Website](https://avrae.io/) and opening up the developer console. Then, go to Storage, Local Storage, and copy the value of the avrae_token.

- Do you mean an Avrae Developer Console or like, Chrome/Firefox/Edge? I can't find it in either. Would it be possible to get a (censored) screenshot perhaps?

**Comment by 1drturtle** [comment]
This would be your browser's developer console. Here's a screenshot from a firefox perspective.
![image](https://user-images.githubusercontent.com/16567386/172492559-262d5b4e-6760-4f78-8630-8a811c93fd74.png)

**Comment by ianfhunter** [comment]
Thank you very much!
My developer tools were slightly different but I was able to find it:
![image](https://user-images.githubusercontent.com/1540737/172659183-607819df-7d6e-4440-9512-e5f725f73f89.png)
